version: "3.6"

services:
  ollama:
    tty: true
    image: ollama/ollama:${SOFTWARE_VERSION_TAG}
    restart: always
    volumes:
      - ./ollama:/root/.ollama

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    restart: always
    depends_on:
      - ollama
    ports:
      - 172.17.0.1:13589:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    volumes:
      - ./ollama-webui:/app/backend/data
